trigger:
  - master
  - releases/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '22.x'
  appName: 'fc-oay-appsvc-prd-up2-01'

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
        - task: UseNode@1
          inputs:
            version: $(nodeVersion)
          displayName: 'Install Node.js'
        - script: |
            npm install
          displayName: 'Install dependencies'
        - script: |
            npm run build
          displayName: 'Build project'
        - task: CopyFiles@2
          inputs:
            Contents: 'dist/**'
            TargetFolder: $(Build.ArtifactStagingDirectory)
          displayName: 'Copying /dist folder'
        - task: CopyFiles@2
          inputs:
            Contents: 'data/**'
            TargetFolder: $(Build.ArtifactStagingDirectory)/dist
          displayName: 'Copying /data folder'
        - task: CopyFiles@2
          inputs:
            Contents: 'src/assets/images/*'
            TargetFolder: $(Build.ArtifactStagingDirectory)/dist
          displayName: 'Copying /images folder'
        - task: PublishBuildArtifacts@1

  - stage: Deploy
    jobs:
      - deployment: DeployJob
        environment: 'Production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'fc-oay-appreg-prd-up2-01'
                    appType: webApp
                    appName: '$(appName)'
                    slotName: 'Production'
                    package: '$(Pipeline.Workspace)/drop/dist'
                  displayName: 'Deploy to Azure Web App Service'
